# Generated by Django 6.0.4 on 2026-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_build_courses',
            field=models.BooleanField(default=False),
        ),
    ]
