# Generated by Django 6.0.5 on 2026-06-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
