# Generated by Django 6.0.5 on 2026-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_pending_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='send_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
