# Generated by Django 6.0.6 on 2026-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_can_edit_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
