/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim":         "rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed":           "rgb(var(--color-on-primary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant":  "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
        surface:                      "rgb(var(--color-surface) / <alpha-value>)",
        "on-background":              "rgb(var(--color-on-background) / <alpha-value>)",
        "outline-variant":            "rgb(var(--color-outline-variant) / <alpha-value>)",
        "error-container":            "rgb(var(--color-error-container) / <alpha-value>)",
        "on-secondary":               "rgb(var(--color-on-secondary) / <alpha-value>)",
        "surface-container-low":      "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-bright":             "rgb(var(--color-surface-bright) / <alpha-value>)",
        "inverse-on-surface":         "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "secondary-fixed-dim":        "rgb(var(--color-secondary-fixed-dim) / <alpha-value>)",
        "surface-dim":                "rgb(var(--color-surface-dim) / <alpha-value>)",
        "on-tertiary":                "rgb(var(--color-on-tertiary) / <alpha-value>)",
        "on-surface-variant":         "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "secondary-fixed":            "rgb(var(--color-secondary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)",
        "inverse-primary":            "rgb(var(--color-inverse-primary) / <alpha-value>)",
        "on-primary-container":       "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "surface-container":          "rgb(var(--color-surface-container) / <alpha-value>)",
        outline:                      "rgb(var(--color-outline) / <alpha-value>)",
        "primary-fixed":              "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "on-error-container":         "rgb(var(--color-on-error-container) / <alpha-value>)",
        "surface-container-high":     "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "on-primary-fixed-variant":   "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "on-error":                   "rgb(var(--color-on-error) / <alpha-value>)",
        "on-tertiary-fixed":          "rgb(var(--color-on-tertiary-fixed) / <alpha-value>)",
        "secondary-container":        "rgb(var(--color-secondary-container) / <alpha-value>)",
        "on-tertiary-container":      "rgb(var(--color-on-tertiary-container) / <alpha-value>)",
        "inverse-surface":            "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "on-surface":                 "rgb(var(--color-on-surface) / <alpha-value>)",
        tertiary:                     "rgb(var(--color-tertiary) / <alpha-value>)",
        "on-secondary-container":     "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "surface-container-highest":  "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "surface-variant":            "rgb(var(--color-surface-variant) / <alpha-value>)",
        primary:                      "rgb(var(--color-primary) / <alpha-value>)",
        secondary:                    "rgb(var(--color-secondary) / <alpha-value>)",
        background:                   "rgb(var(--color-background) / <alpha-value>)",
        error:                        "rgb(var(--color-error) / <alpha-value>)",
        "surface-container-lowest":   "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "on-secondary-fixed":         "rgb(var(--color-on-secondary-fixed) / <alpha-value>)",
        "on-primary":                 "rgb(var(--color-on-primary) / <alpha-value>)",
        "primary-fixed-dim":          "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
        "tertiary-fixed":             "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
        "surface-tint":               "rgb(var(--color-surface-tint) / <alpha-value>)",
        "tertiary-container":         "rgb(var(--color-tertiary-container) / <alpha-value>)",
        "primary-container":          "rgb(var(--color-primary-container) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"],
      },
      boxShadow: {
        nebula:        "0 0 60px 10px rgba(162, 201, 255, 0.08)",
        "nebula-lg":   "0 0 80px 20px rgba(162, 201, 255, 0.12)",
        "xp-glow":     "0 0 12px rgba(103, 223, 112, 0.4)",
        "streak-glow": "0 0 12px rgba(255, 181, 137, 0.4)",
      },
      keyframes: {
        "fade-in":       { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-in-up":    { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "scale-in":      { from: { opacity: "0", transform: "scale(0.96)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-in-right": { from: { opacity: "0", transform: "translateX(24px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        "pop":           { "0%": { transform: "scale(0.8)", opacity: "0" }, "60%": { transform: "scale(1.08)" }, "100%": { transform: "scale(1)", opacity: "1" } },
        float:           { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-6px)" } },
      },
      animation: {
        "fade-in":        "fade-in 0.3s ease-out both",
        "fade-in-up":     "fade-in-up 0.35s ease-out both",
        "scale-in":       "scale-in 0.2s ease-out both",
        "slide-in-right": "slide-in-right 0.3s ease-out both",
        pop:              "pop 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        float:            "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
