# Generated by Django 6.0.3 on 2026-04-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('chapter', models.CharField(max_length=255)),
                ('concept', models.CharField(blank=True, max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('case_study', 'Case Study'), ('short_answer', 'Short Answer')], max_length=50)),
                ('marks', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoubtTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoubtResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, help_text='If AI generated, the confidence out of 1.0', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubt_responses', to=settings.AUTH_USER_MODEL)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ai_engine.doubtticket')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('config', models.JSONField(help_text='Stores the parameters used to generate this paper')),
                ('secure_pdf_path', models.FileField(blank=True, null=True, upload_to='generated_papers/')),
                ('share_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='ai_engine.generatedpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_papers', to='ai_engine.questionbank')),
            ],
            options={
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
