# Generated by Django 6.0.3 on 2026-04-07 16:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('board', models.CharField(blank=True, max_length=50)),
                ('class_grade', models.CharField(blank=True, max_length=20)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Source Document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DoubtTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoubtResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, help_text='If AI generated, the confidence out of 1.0', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubt_responses', to=settings.AUTH_USER_MODEL)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ai_engine.doubtticket')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, help_text='Stores the parameters used to generate this paper', null=True)),
                ('secure_pdf_path', models.FileField(blank=True, null=True, upload_to='generated_papers/')),
                ('share_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('class_grade', models.CharField(blank=True, max_length=20)),
                ('board', models.CharField(blank=True, max_length=50)),
                ('total_marks', models.PositiveIntegerField(default=80)),
                ('duration_mins', models.PositiveIntegerField(default=180)),
                ('instructions', models.TextField(blank=True)),
                ('is_template', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ASSERTION_REASON', 'Assertion & Reason'), ('VERY_SHORT', 'Very Short Answer'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('CASE', 'Case Study')], max_length=20)),
                ('marks_per_question', models.PositiveIntegerField()),
                ('question_count', models.PositiveIntegerField()),
                ('difficulty_mix', models.JSONField(blank=True, default=dict)),
                ('bloom_mix', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ai_engine.questionpaper')),
            ],
            options={
                'verbose_name': 'Paper Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('chapter', models.CharField(db_index=True, max_length=100)),
                ('concept', models.CharField(blank=True, max_length=150)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ASSERTION_REASON', 'Assertion & Reason'), ('VERY_SHORT', 'Very Short Answer'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('CASE', 'Case Study')], db_index=True, max_length=20)),
                ('marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10)),
                ('bloom_level', models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=20)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('has_image', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('question_hash', models.CharField(max_length=64, unique=True)),
                ('is_ai_generated', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='ai_engine.sourcedocument')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Question Bank',
                'ordering': ['subject', 'chapter', 'question_type'],
            },
        ),
        migrations.CreateModel(
            name='FailedIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.TextField()),
                ('error_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='ai_engine.sourcedocument')),
            ],
            options={
                'verbose_name': 'Failed Ingestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_section', models.PositiveSmallIntegerField()),
                ('marks_override', models.PositiveIntegerField(blank=True, null=True)),
                ('was_ai_generated', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='ai_engine.papersection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_appearances', to='ai_engine.questionbank')),
            ],
            options={
                'verbose_name': 'Paper Question',
                'ordering': ['order_in_section'],
                'unique_together': {('section', 'order_in_section')},
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=1)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ai_engine.questionbank')),
            ],
            options={
                'verbose_name': 'MCQ Option',
                'ordering': ['order'],
                'unique_together': {('question', 'option_label')},
            },
        ),
        migrations.CreateModel(
            name='CaseStudyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveSmallIntegerField()),
                ('part_text', models.TextField()),
                ('part_answer', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ASSERTION_REASON', 'Assertion & Reason'), ('VERY_SHORT', 'Very Short Answer'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('CASE', 'Case Study')], default='SHORT', max_length=20)),
                ('marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_parts', to='ai_engine.questionbank')),
            ],
            options={
                'verbose_name': 'Case Study Part',
                'ordering': ['part_number'],
                'unique_together': {('parent_question', 'part_number')},
            },
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['subject', 'chapter', 'question_type', 'difficulty'], name='idx_question_filter'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['is_ai_generated', 'is_verified'], name='idx_ai_quality'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['subject', 'chapter', 'bloom_level'], name='idx_bloom'),
        ),
    ]
