# Generated by Django 6.0.4 on 2026-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudypart',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudypart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/case_parts/'),
        ),
        migrations.AddField(
            model_name='casestudypart',
            name='image_description',
            field=models.TextField(blank=True, help_text='Alt text or AI-generated description of the figure'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='image_description',
            field=models.TextField(blank=True, help_text='Alt text or AI-generated description of the figure'),
        ),
    ]
