# Generated by Django 6.0.4 on 2026-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_casestudypart_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypart',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ASSERTION_REASON', 'Assertion & Reason'), ('VERY_SHORT', 'Very Short Answer'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('CASE', 'Case Study'), ('REARRANGE', 'Rearrange')], default='SHORT', max_length=20),
        ),
        migrations.AlterField(
            model_name='papersection',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ASSERTION_REASON', 'Assertion & Reason'), ('VERY_SHORT', 'Very Short Answer'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('CASE', 'Case Study'), ('REARRANGE', 'Rearrange')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ASSERTION_REASON', 'Assertion & Reason'), ('VERY_SHORT', 'Very Short Answer'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('CASE', 'Case Study'), ('REARRANGE', 'Rearrange')], db_index=True, max_length=20),
        ),
    ]
