# Generated by Django 6.0.6 on 2026-06-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_questionpaper_status_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
