# Generated by Django 6.0.4 on 2026-04-09 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('class_grade', models.CharField(choices=[('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5)),
                ('board', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('card_type', models.CharField(choices=[('CONCEPT', 'Concept Card'), ('FORMULA', 'Formula Card'), ('EXAMPLE', 'Example Card'), ('MNEMONIC', 'Mnemonic Card'), ('SUMMARY', 'Summary Card')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('concept', models.CharField(blank=True, max_length=150)),
                ('has_formula', models.BooleanField(default=False)),
                ('formula_text', models.TextField(blank=True)),
                ('example_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('LESSON', 'Lesson Node'), ('CHAPTER_TEST', 'Chapter Test')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_bonus', models.BooleanField(default=False)),
                ('youtube_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('practice_question_count', models.PositiveIntegerField(default=5)),
                ('starting_lives', models.PositiveIntegerField(default=3)),
                ('test_question_count', models.PositiveIntegerField(default=10)),
                ('test_pass_percentage', models.PositiveIntegerField(default=70)),
                ('question_filter', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('purpose', models.CharField(choices=[('PREREQUISITE', 'Course Prerequisites'), ('POST_NODE', 'Post-Node Revision'), ('SIDE_REVISION', 'Side Revision Node')], max_length=20)),
                ('cards', models.ManyToManyField(through='learning.DeckCard', to='learning.flashcard')),
                ('course_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prereq_decks', to='learning.courseunit')),
                ('learning_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_decks', to='learning.learningnode')),
            ],
            options={
                'verbose_name': 'Flashcard Deck',
            },
        ),
        migrations.AddField(
            model_name='deckcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcarddeck'),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('class_grade', models.CharField(choices=[('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to='learning.courseunit')),
            ],
        ),
        migrations.AddField(
            model_name='learningnode',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning.learningpath'),
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL_BLANK', 'Fill in the Blank'), ('TRUE_FALSE', 'True/False'), ('MATCH', 'Match')], max_length=20)),
                ('question_text', models.TextField()),
                ('options_json', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.CharField(max_length=500)),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('concept', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.learningnode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RevisionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('xp_reward', models.PositiveIntegerField(default=15)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('appears_after_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_revision', to='learning.learningnode')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_nodes', to='learning.learningpath')),
            ],
            options={
                'verbose_name': 'Revision Node',
            },
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='revision_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='learning.revisionnode'),
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningnode')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.lessonquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deckcard',
            unique_together={('deck', 'card')},
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('marked_known', models.BooleanField(default=False)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'card')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='learningnode',
            unique_together={('path', 'order')},
        ),
        migrations.CreateModel(
            name='NodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='LOCKED', max_length=20)),
                ('current_step', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('VIDEO_DONE', 'Video Watched'), ('PRACTICE', 'In Practice'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('lives_remaining', models.PositiveIntegerField(default=3)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard_shown', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='learning.learningnode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'node')},
            },
        ),
        migrations.CreateModel(
            name='RevisionNodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('revision_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.revisionnode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'revision_node')},
            },
        ),
        migrations.CreateModel(
            name='UnitPrerequisiteSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.courseunit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course_unit')},
            },
        ),
        migrations.CreateModel(
            name='WeakSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('last_wrong_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_spots', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-wrong_count'],
                'unique_together': {('student', 'concept', 'subject', 'chapter')},
            },
        ),
    ]
