# Generated by Django 6.0.4 on 2026-04-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(help_text='E.g., LESSON_VIDEO, CHAPTER_TEST_10', max_length=50)),
                ('config_json', models.JSONField(default=dict, help_text='Default configuration JSON for Node and Questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
