# Generated by Django 6.0.4 on 2026-04-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_contenttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL_BLANK', 'Fill in the Blank'), ('TRUE_FALSE', 'True/False'), ('MATCH', 'Match'), ('PROOF_PUZZLE', 'Proof Puzzle')], max_length=20),
        ),
    ]
