# Generated by Django 6.0.4 on 2026-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_courseunit_assigned_teacher_lessonquestion_source_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningnode',
            name='description',
            field=models.TextField(blank=True, help_text='About this lesson text shown on the video page'),
        ),
        migrations.AddField(
            model_name='learningnode',
            name='objectives_json',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objective strings'),
        ),
    ]
