# Generated by Django 6.0.4 on 2026-04-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_learningnode_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningnode',
            name='lab_category',
            field=models.CharField(blank=True, choices=[('INTERACTIVE', 'Interactive Explorer'), ('CREATIVE', 'Creative Builder'), ('SIMULATION', 'Simulation')], max_length=20),
        ),
        migrations.AddField(
            model_name='learningnode',
            name='lab_required_completions',
            field=models.PositiveIntegerField(default=0, help_text='Number of non-lab nodes that must be completed to unlock this lab'),
        ),
        migrations.AddField(
            model_name='learningnode',
            name='lab_type',
            field=models.CharField(blank=True, help_text='Registry key, e.g. HCF_LCM_VISUALIZER', max_length=60),
        ),
        migrations.AddField(
            model_name='nodeprogress',
            name='lab_artifact',
            field=models.JSONField(blank=True, help_text='Stores lab output for CREATIVE labs', null=True),
        ),
        migrations.AlterField(
            model_name='learningnode',
            name='node_type',
            field=models.CharField(choices=[('LESSON', 'Lesson Node'), ('CHAPTER_TEST', 'Chapter Test'), ('LAB', 'Lab Node')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL_BLANK', 'Fill in the Blank'), ('TRUE_FALSE', 'True/False'), ('MATCH', 'Match'), ('PROOF_PUZZLE', 'Proof Puzzle'), ('REARRANGE', 'Rearrange / Picker'), ('MULTI_SELECT', 'Select All That Apply')], max_length=20),
        ),
    ]
