# Generated by Django 6.0.4 on 2026-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_add_lab_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningnode',
            name='unlock_min_stars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum stars (1-3) required on the preceding lesson node to unlock this node. 0 = no requirement.'),
        ),
    ]
