# Generated by Django 6.0.4 on 2026-05-09 14:54

import django.db.models.deletion
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_mocktestempt'),
        ('users', '0003_add_can_build_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('invite_code', models.CharField(default=learning.models._invite_code, max_length=8, unique=True)),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='learning.studygroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.studentprofile')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('group', 'student')},
            },
        ),
    ]
