# Generated by Django 6.0.6 on 2026-06-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_chat_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='question_id',
            field=models.IntegerField(blank=True, help_text='QuestionBank PK for question-mode doubts', null=True),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL_BLANK', 'Fill in the Blank'), ('TRUE_FALSE', 'True/False'), ('MATCH', 'Match'), ('PROOF_PUZZLE', 'Proof Puzzle'), ('REARRANGE', 'Rearrange / Picker'), ('MULTI_SELECT', 'Select All That Apply'), ('SHORT_ANSWER', 'Short Answer'), ('LONG_ANSWER', 'Long Answer')], max_length=20),
        ),
    ]
