# Generated by Django 6.0.6 on 2026-06-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_add_image_fields_and_answer_types_to_lessonquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningnode',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
