# Generated by Django 6.0.6 on 2026-06-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_learningnode_is_archived_lessonquestion_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='max_members',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
