# Generated by Django 6.0.6 on 2026-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_scope_g10_chapter_test_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_images/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='image_description',
            field=models.TextField(blank=True, help_text='Alt text / caption for the image'),
        ),
    ]
